site_name: Django Util

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - admin.md
  - choices.md
  - constants.md
  - fields.md
  - models.md
  - signals.md
  - utility.md
  - validators.md
